export { default as ArticleEditor } from './ArticleEditor.vue'
export { default } from './ArticleEditor.vue'
export { createEmptyDocument } from './editor/document'
export { getCurrentProtocol } from './protocol/current-protocol'
export { toProtocolJSON, validateProtocolDocument, validateProtocolV1Document } from './editor/protocol'
export type { ArticleEditorProps, ArticleEditorExpose, ArticleEditorError } from './editor/public-types'
export type { ImageUploadHandler, ImageUploadContext, ImageUploadResult } from './editor/public-types'
export type { ProseMirrorJSON, MarkJSON, ValidationResult } from './editor/types'
export type { ResourceQuestionData, ResourceQuestionAttrs, ResourceQuestionImage, ResourceQuestionOption, ResourceQuestionPickerScope } from './editor/resource-question'
